<?php
/**
 * ItemsApi
 * PHP version 5
 *
 * @category Class
 * @package  EzzeSiftuz\OrdersV2
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Orders
 *
 * This API documentation describes all endpoints for orders
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.16
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace EzzeSiftuz\OrdersV2\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use EzzeSiftuz\OrdersV2\ApiException;
use EzzeSiftuz\OrdersV2\Configuration;
use EzzeSiftuz\OrdersV2\HeaderSelector;
use EzzeSiftuz\OrdersV2\ObjectSerializer;

/**
 * ItemsApi Class Doc Comment
 *
 * @category Class
 * @package  EzzeSiftuz\OrdersV2
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ItemsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation cancelPartnerOrderPositionItems
     *
     * Cancel a single position item
     *
     * @param  string $sales_order_id sales_order_id (required)
     * @param  string[] $position_item_id position_item_id (required)
     *
     * @throws \EzzeSiftuz\OrdersV2\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function cancelPartnerOrderPositionItems($sales_order_id, $position_item_id)
    {
        $this->cancelPartnerOrderPositionItemsWithHttpInfo($sales_order_id, $position_item_id);
    }

    /**
     * Operation cancelPartnerOrderPositionItemsWithHttpInfo
     *
     * Cancel a single position item
     *
     * @param  string $sales_order_id (required)
     * @param  string[] $position_item_id (required)
     *
     * @throws \EzzeSiftuz\OrdersV2\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function cancelPartnerOrderPositionItemsWithHttpInfo($sales_order_id, $position_item_id)
    {
        $returnType = '';
        $request = $this->cancelPartnerOrderPositionItemsRequest($sales_order_id, $position_item_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation cancelPartnerOrderPositionItemsAsync
     *
     * Cancel a single position item
     *
     * @param  string $sales_order_id (required)
     * @param  string[] $position_item_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function cancelPartnerOrderPositionItemsAsync($sales_order_id, $position_item_id)
    {
        return $this->cancelPartnerOrderPositionItemsAsyncWithHttpInfo($sales_order_id, $position_item_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation cancelPartnerOrderPositionItemsAsyncWithHttpInfo
     *
     * Cancel a single position item
     *
     * @param  string $sales_order_id (required)
     * @param  string[] $position_item_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function cancelPartnerOrderPositionItemsAsyncWithHttpInfo($sales_order_id, $position_item_id)
    {
        $returnType = '';
        $request = $this->cancelPartnerOrderPositionItemsRequest($sales_order_id, $position_item_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'cancelPartnerOrderPositionItems'
     *
     * @param  string $sales_order_id (required)
     * @param  string[] $position_item_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function cancelPartnerOrderPositionItemsRequest($sales_order_id, $position_item_id)
    {
        // verify the required parameter 'sales_order_id' is set
        if ($sales_order_id === null || (is_array($sales_order_id) && count($sales_order_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $sales_order_id when calling cancelPartnerOrderPositionItems'
            );
        }
        // verify the required parameter 'position_item_id' is set
        if ($position_item_id === null || (is_array($position_item_id) && count($position_item_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $position_item_id when calling cancelPartnerOrderPositionItems'
            );
        }

        $resourcePath = '/orders/{salesOrderId}/items/{positionItemId}/cancellation';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($sales_order_id !== null) {
            $resourcePath = str_replace(
                '{' . 'salesOrderId' . '}',
                ObjectSerializer::toPathValue($sales_order_id),
                $resourcePath
            );
        }
        // path params
        if ($position_item_id !== null) {
            $resourcePath = str_replace(
                '{' . 'positionItemId' . '}',
                ObjectSerializer::toPathValue($position_item_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation confirmPartnerOrderPositionItems
     *
     * Confirm a single position item
     *
     * @param  string $sales_order_id sales_order_id (required)
     * @param  string[] $position_item_id position_item_id (required)
     *
     * @throws \EzzeSiftuz\OrdersV2\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function confirmPartnerOrderPositionItems($sales_order_id, $position_item_id)
    {
        $this->confirmPartnerOrderPositionItemsWithHttpInfo($sales_order_id, $position_item_id);
    }

    /**
     * Operation confirmPartnerOrderPositionItemsWithHttpInfo
     *
     * Confirm a single position item
     *
     * @param  string $sales_order_id (required)
     * @param  string[] $position_item_id (required)
     *
     * @throws \EzzeSiftuz\OrdersV2\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function confirmPartnerOrderPositionItemsWithHttpInfo($sales_order_id, $position_item_id)
    {
        $returnType = '';
        $request = $this->confirmPartnerOrderPositionItemsRequest($sales_order_id, $position_item_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation confirmPartnerOrderPositionItemsAsync
     *
     * Confirm a single position item
     *
     * @param  string $sales_order_id (required)
     * @param  string[] $position_item_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function confirmPartnerOrderPositionItemsAsync($sales_order_id, $position_item_id)
    {
        return $this->confirmPartnerOrderPositionItemsAsyncWithHttpInfo($sales_order_id, $position_item_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation confirmPartnerOrderPositionItemsAsyncWithHttpInfo
     *
     * Confirm a single position item
     *
     * @param  string $sales_order_id (required)
     * @param  string[] $position_item_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function confirmPartnerOrderPositionItemsAsyncWithHttpInfo($sales_order_id, $position_item_id)
    {
        $returnType = '';
        $request = $this->confirmPartnerOrderPositionItemsRequest($sales_order_id, $position_item_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'confirmPartnerOrderPositionItems'
     *
     * @param  string $sales_order_id (required)
     * @param  string[] $position_item_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function confirmPartnerOrderPositionItemsRequest($sales_order_id, $position_item_id)
    {
        // verify the required parameter 'sales_order_id' is set
        if ($sales_order_id === null || (is_array($sales_order_id) && count($sales_order_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $sales_order_id when calling confirmPartnerOrderPositionItems'
            );
        }
        // verify the required parameter 'position_item_id' is set
        if ($position_item_id === null || (is_array($position_item_id) && count($position_item_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $position_item_id when calling confirmPartnerOrderPositionItems'
            );
        }

        $resourcePath = '/orders/{salesOrderId}/items/{positionItemId}/confirmation';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($sales_order_id !== null) {
            $resourcePath = str_replace(
                '{' . 'salesOrderId' . '}',
                ObjectSerializer::toPathValue($sales_order_id),
                $resourcePath
            );
        }
        // path params
        if ($position_item_id !== null) {
            $resourcePath = str_replace(
                '{' . 'positionItemId' . '}',
                ObjectSerializer::toPathValue($position_item_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
