<?php
/**
 * ItemsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  EzzeSiftuz\OrdersV2
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Orders
 *
 * This API documentation describes all endpoints for orders
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.16
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace EzzeSiftuz\OrdersV2;

use EzzeSiftuz\OrdersV2\Configuration;
use EzzeSiftuz\OrdersV2\ApiException;
use EzzeSiftuz\OrdersV2\ObjectSerializer;

/**
 * ItemsApiTest Class Doc Comment
 *
 * @category Class
 * @package  EzzeSiftuz\OrdersV2
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ItemsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for cancelPartnerOrderPositionItems
     *
     * Cancel a single position item.
     *
     */
    public function testCancelPartnerOrderPositionItems()
    {
    }

    /**
     * Test case for confirmPartnerOrderPositionItems
     *
     * Confirm a single position item.
     *
     */
    public function testConfirmPartnerOrderPositionItems()
    {
    }
}
